### ISSUE TITLE
Getting started guide documentation

### ISSUE THREAD

**Issue by KenEucker** [eddeee888/route-codegen#105]
**Describe the solution you'd like**
I would like to see a getting started guide either in the README or in the sample folder, that outlines how to use the results of this package. If I were getting started with React Router and wanting to generate my routes, how would I use this package to aid me?

**Describe alternatives you've considered**
I can generate my route files and that part makes sense to me, but where do I go from here? I want to be able to import the resulting `rootIndex` file into my Router.tsx file and use it, but it's not clear to me how I can accomplish that.

**Additional context**
Please halp!

I was hoping to be able to come here and provide this very solution, a getting started guide, but I wasn't able to get started. I would be happy to contribute that if you can help me understand this a bit more, @eddeee888.

Cheers, and thanks for contributing to FOSS!

**Comment by KenEucker** [comment]
Here's what I am envisioning I would be able to do, given the output of this package:

```
// router.tsx

import * as React from 'react'
import { Switch, BrowserRouter, Route } from 'react-router-dom'
import * as routes from './routes'

export default function Router() {
	return (<BrowserRouter>
		<Switch>
			{routes.map(({path, component}, key) => {
				<Route key={key} path={path} exact component={component} />
			})}
		</Switch>
	</BrowserRouter>)
}
```

note: I didn't see a way for me to specify the component that I would like to associate with each route. If that's not supported or is out of scope, then I was hoping to be able to infer the component to load based on the name of the route.

**Comment by eddeee888** [comment]
Hello @KenEucker, sorry I didn't see this issue until now!

Thanks for your suggestions! I like how clean your solution is. However, in larger apps, it could be better to see the routes fully displayed. It is commonly used as the point of reference to see how the app works. I have also encountered some use cases where routes can be nested so using a loop sometimes won't work.

The generated values are intended to be used to help keep path pattern and type consistency throughout the apps. A typical router file looks something like this: 

```tsx
import * as React from 'react'
import { Switch, BrowserRouter, Route } from 'react-router-dom'
import * as routes from './routes'

export default function Router() {
  return (
    <BrowserRouter>
      <Switch>
	<Route path={routes.patternPath1} exact component={Component1} />
        <Route path={routes.patternPath2} exact render={(props: RouteComponentProps<routes.PathParamsPattern2>) => <Component2 />} />
        <Route path={routes.patternPath3Base}>
            <Switch>
                <Route path={routes.patternPath3Subpath1} exact ... />
                <Route path={routes.patternPath3Subpath2} exact ... />
            </Switch>
        </Route>
      </Switch>
    </BrowserRouter>
  )
}
```

Let me know if you have other questions!

**Comment by KenEucker** [comment]
@eddeee888 thanks for getting back to me!

I can appreciate that seeing the routes in a single file, where the components are loaded along with anything else that may be required in setting up those routes, is a good way for developers to understand how the app works. This may just be a case of me not keeping it simple.

Thanks for contributing to Free and Open-Source Software!
